apiVersion: apps/v1
kind: Deployment
metadata:
  name: error-lookup-tool
  labels:
    app.kubernetes.io/name: error-lookup-tool
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: error-lookup-tool
  template:
    metadata:
      labels:
        app.kubernetes.io/name: error-lookup-tool
    spec:
      containers:
        - name: error-lookup-tool
          image: "{{ .Values.image.tag }}"
          env:
            - name: PORT
              value: "8080"
            - name: NODE_ENV
              value: "production"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10