apiVersion: apps/v1
kind: Deployment
metadata:
  name: error-lookup-tool
  labels:
    app.kubernetes.io/name: error-lookup-tool
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: error-lookup-tool
  template:
    metadata:
      labels:
        app.kubernetes.io/name: error-lookup-tool
    spec:
      containers:
        - name: error-lookup-tool
          image: "{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          resources: {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always