apiVersion: v1
kind: Service
metadata:
  name: error-lookup-tool
  labels:
    app.kubernetes.io/name: error-lookup-tool
spec:
  selector:
    app.kubernetes.io/name: error-lookup-tool
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080