replicaCount: 1

image:
  repository: ghcr.io/kiiskila-bcgov/icm-error-lookup-tool
  tag: test
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}